### PR TITLE
Nix 2.4

### PR DESCRIPTION
**Pull request by typetetris**
Hi there!

Just took the work of @bbenne10 and @Mic92  and found the remaining error.
Tests are green now.

Have fun!

### CODE REVIEW

**Comment by typetetris** [comment]
Fixes #109 and #149

**Comment by bbenne10** [comment]
Ill check this out this afternoon, but I need to get the WIP commit out of my branch and will rebase your commits on top before I approve.

**Comment by bbenne10** [comment]
Read this over and all lools good excepting the WIP commit and one or two style nitpicks. Once my kid goes to sleep this evening, Ill fix up my part of the git history, add a small style fix and merge.

Related: We should bump to at least 1.7 once merged.

**Comment by bbenne10** [comment]
Closed with latest push (2dfdd127bd84a275a185822b64a2e53a1091e3dc)! Thank you for your contribution!

**Pull request closed without merging**
