### PR TITLE
add NIX_BIN_PREFIX to hardcode nix

### PR DESCRIPTION
**Pull request by Mic92**

### CODE REVIEW

**Comment by cpcloud** [comment]
I just bisected my configuration, and somehow this commit causes every line of stdout to be duplicated in any project that uses `direnv`.

I'm using `home-manager` with the `programs.direnv.enableNixDirenvIntegration = true;`.

**Comment by cpcloud** [comment]
Ok, after changing `nixFlakes` to `nix` in `default.nix` on `master`, the double logging goes away. Is this a bug in the nix binaries under `nixFlakes`?

**Comment by cpcloud** [comment]
In the meantime, it's easy enough to override `nixFlakes` with `nix` in an overlay.

**Comment by Mic92** [comment]
This was a bug in nixUnstable at some point. It got fixed however eventually. You must use an old version.

**Comment by cpcloud** [comment]
I'm using `niv` to manage `nixpkgs` and running against `nixos-unstable-small`, so I assume that I have the latest-but-not-master-mostly-reliably-passing versions of everything.

**Pull request merged**
