### PR TITLE
drop nix_direnv_watch_file - instead parse DIRENV_WATCHES

### PR DESCRIPTION
**Pull request by Mic92**

### CODE REVIEW

**Comment by Mic92** [comment]
@mergify queue

**Comment by polygon** [comment]
Using `nix_direnv_watch_file` is now causing `direnv` to fail completely until changed? How would I keep a `.envrc` working with older and newer versions of `direnv`?

**Comment by Mic92** [comment]
> `nix_direnv_watch_file`

It still works, it just prints a warning:

```
direnv: loading ~/.homesick/repos/dotfiles/.envrc
direnv: `nix_direnv_watch_file` is deprecated - use `watch_file`
direnv: using flake
```

**Comment by Mic92** [comment]
To get rid of the warning you can use:

```
if ! has nix_direnv_version || ! nix_direnv_version 2.5.0; then
  source_url "https://raw.githubusercontent.com/nix-community/nix-direnv/2.5.0/direnvrc" "sha256-5XwUul/GUzj52MC5LvjHaZXDW2iLnl93tEQSYm9f3Rc="
fi
watch_file foo.nix
use nix
```

**Pull request merged**
