### PR TITLE
Use nix 2.4 features

### PR DESCRIPTION
**Pull request by Mic92**
fixes https://github.com/nix-community/nix-direnv/issues/109

### CODE REVIEW

**Comment by Mic92** [comment]
I still need to fix the tests that have old expectations and add some new ones for the argument parser.

**Comment by nifoc** [comment]
I just ran into #109 myself, so I'm eager to get this merged. Can I somehow help with moving this PR along?

**Comment by Mic92** [comment]
@nifoc I think this broke caching. But I have not fixed it yet.

**Comment by Mic92** [comment]
@lilyball it breaks caching just now. My work life seems to calm down a bit so I can back to opensource stuff again.

**Comment by bbenne10** [comment]
#91 explicitly disabled shell hook on cached devshell execution when calling `use flake`. 
#109 and #149 are both about the lack of shellHook on cached execution.

Personally, I think we should ensure that shellHook is called on execution in both `use nix` and `use flake` workflows. 
Leaving a note here for whoever gets around to this task first.

**Comment by bbenne10** [comment]
[This branch on my fork](https://github.com/bbenne10/nix-direnv/tree/nix24) has some in-progress work on this. 

I have yet to figure out why the tests are consistently failing in different ways between different CI and my laptop. 
The functionality seems to *work* locally, but the tests are just not exhibiting the exact same behavior.

Still working on it.

**Comment by bbenne10** [comment]
With the merge of #153, I feel pretty confident in saying that this is complete! :tada:

**Pull request closed without merging**
