### PR TITLE
Check nix version directly

### PR DESCRIPTION
**Pull request by pinselimo**
This PR resolves issue #305 by querying the nix version through ``nix --version`` and testing that.

It also adds error reporting of the current nix version in case the test fails.

### CODE REVIEW

**Comment by bbenne10** [comment]
This LGTM, but I'd like to have @Mic92 make sure this doesn't break some other obscure usecase that's not quite tested or stated well enough. 

I personally think this is better: We're explicitly testing for the thing we're stating fails and not redirecting any other failure case out of the user's site. With flakes shipped in stable versions of nix for a while now, I (personally) don't expect too many differences between what they look like now vs when they are deemed "stable" (though I do wish that would happen sooner rather than later...)

**Comment by bbenne10** [comment]
Oops. Looks like you did not run shellcheck over the file. Please do so and fix up the reported errors. (You can see the ones it reported in the CI failure logs)

**Comment by pinselimo** [comment]
Thanks @bbenne10 ! Fixed it up and ran the tests locally. Had to introduce an intermediate variable.

**Comment by bbenne10** [comment]
With no response from @Mic92, I'm going to merge this. We'll handle any edge cases in a new issue or PR.

**Comment by pinselimo** [comment]
Thx @bbenne10! I've tried to test the regex against all abominations of a nix version string I could come up with and it held up. Let's hope it stays this way.

**Pull request merged**
